const playlist = [
    {
        id: 1,
        title: "Skanking Sweet",
        genre: "reggae",
        artist: "Chronix",
        img: "./images/chronixx.jpeg",
        desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
        id: 2,
        title: "Wet Dreamz",
        genre: "hiphop",
        artist: "J Cole",
        img: "./images/Jcole.jpeg",
        desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
        id: 3,
        title: "Suzana",
        genre: "afro",
        artist: "Sauti Sol",
        img: "./images/sauti.jpeg",
        desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
        id: 4,
        title: "One Love",
        genre: "reggae",
        artist: "Bob Marley",
        img: "./images/bob.png",
        desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
        id: 5,
        title: "A Milli",
        genre: "hiphop",
        artist: "Lil Wayne",
        img: "./images/lilwayne.jpeg",
        desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
        id: 6,
        title: "Damini",
        genre: "afro",
        artist: "Burna",
        img: "./images/burna.jpeg",
        desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
        id: 7,
        title: "Stony Hill",
        genre: "reggae",
        artist: "Damian",
        img: "./images/Damian.jpeg",
        desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
        id: 8,
        title: "Illmatic",
        genre: "hiphop",
        artist: "Nas",
        img: "./images/Nas.jpeg",
        desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
        id: 9,
        title: "Timeless",
        genre: "afro",
        artist: "Davido",
        img: "./images/davido.jpeg",
        desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
];
export default playlist;